type Ticket {
  ticketId: ID,
  title: String,
  description: String,
  createdBy: User,
  assignedTo: User,
  status: String,
  priority: Int,
  createdAt: String,
  dueDate: String,
}

type Query {
  getATicket(ticketId: ID!): Ticket
  getTickets: [Ticket]
  getAssignedTickets: [Ticket]
  getCreatedTickets: [Ticket]
  getArchivedTickets: [Ticket]
  getDeletedTickets: [Ticket]
  getOpenTickets: [Ticket]
}

type Mutation {
  newTicket(
    title: String!,
    description: String,
    assignedTo: String,
    status: String,
    priority: Int!,
    dueDate: String,
  ): Ticket
  updateTicket(
    ticketId: ID!,
    title: String,
    description: String,
    assignedTo: String,
    status: String,
    priority: Int,
    dueDate: String,
  ): Ticket
  archiveTicket(ticketId: String!): Ticket
  deleteTicket(ticketId: String!, mark: Boolean): Ticket
}