type User {
  uid: ID,
  firstName: String,
  middleName: String,
  lastName: String,
  createdAt: String,
  email: String,
  phone: String,
  company: String,
  isTechnician: Boolean,
}

type Query {
  getUserInfo: User
}

type Mutation {
  updateUser(
    uid: ID!,
    firstName: String,
    middleName: String,
    lastName: String,
    email: String,
    phone: String,
    company: String,
    isTechnician: Boolean,
  ): User
}